### ISSUE TITLE
Pimcore Extension Owner

### ISSUE THREAD

**Issue by jeremygnoonan** [DivanteLtd/pimcore-document-copier#3]
Hey there,
We were looking at your plugin on the Pimcore Extensions page and accidentally clicked a button that made us listed as the Author. I've emailed Christian at Pimcore to see if he can have this reverted for us. Just wanted to let you folks know so you don't think we're doing it maliciously! 

We're likely to fork your library for a project we are working on. Thanks for the contribution!

Jeremy

**Comment by t-zilla** [comment]
Cool, no worries
